import type { Metadata } from 'next';
import './globals.css';
import { FlashContextProvider } from '@/features/app/component/flash-context-provider';

export const metadata: Metadata = {
  title: 'ToDo App',
  description: 'Generated by create ToDo App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FlashContextProvider>{children}</FlashContextProvider>
      </body>
    </html>
  );
}
